package com.crane.data.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field as auto-generated by the database.
 * Fields marked with this annotation will be excluded from INSERT statements
 * and their values will be retrieved after insertion if supported by the database.
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGenerated {

  /**
   * The strategy for auto-generation.
   * @return the generation strategy
   */
  Strategy strategy() default Strategy.DATABASE;

  /**
   * Auto-generation strategies
   */
  enum Strategy {
    /**
     * Uses database auto-increment/identity columns
     */
    DATABASE,

    /**
     * Uses UUID generation
     */
    UUID
  }
}
